### ISSUE TITLE
Preprocessing: Add porechop for Nanopore data

### ISSUE THREAD

**Issue by sofstam** [genomic-medicine-sweden/taxprofiler#4]
## Feature
PCR adaptors and low quality bases need to be removed.

## What needs to be done
Porechop is not currently maintained but a lot of nf-core pipelines are still using it and it is already implemented as nf-core module [porechop](https://github.com/nf-core/modules/tree/e20e57f90b6787ac9a010a980cf6ea98bd990046/modules/porechop)

Add preprocessing steps for Nanopore reads for removal of PCR adaptors and low quality bases.

## This can be closed when
- [x] Evaluate the which software that is optimal for trimming (porechop is currently used by nf-core)
- [x] Add porechop/alternative to process the fastq files after the FastQC step

**Comment by sofstam** [comment]
@ljmesi I guess I can close this one, right? We can evaluate the alternative to porechop later in the development.

**Comment by ljmesi** [comment]
Hi @sofstam, Sorry for late reply! I was on holiday until now. Yes, we can close this.
